### ISSUE TITLE
Wrap UDP Classes

### ISSUE THREAD

**Issue by bjorstrom** [billosys/sockets#1]
* [x] Create planning document
* [x] Show Java example
* [x] Show potentially ideal Clojure example
* [x] Identify the classes to wrap
  * [x] wrap DatagramSocket
  * [x] wrap DatagramPacket
  * [x] wrap InetAddress
* [x] Create working example of Clojure code
* [x] Fully document this
* [x] Devise more idiomatic approach
* ~~Create new namespace for improved/second-level API~~
* ~~Implement example of this~~
* ~~Fully document this~~

**Comment by dokkarr** [comment]
Done.
